### PR TITLE
stringifor_string_t: strjoin(array,sep, is_col) for 2D-array function

### PR DESCRIPTION
**Pull request by band-a-prend**
This function is inspired by [matlab join function to combine string array](https://www.mathworks.com/help/matlab/ref/join.html).

_I don’t know how useful the function will be._

This patch offers implementation of function to join 2D-array of strings
into string vector (1D-array).

This functions used early implemented strjoin(array, sep) functions
for string or character 1D-arrays.

The optional separator could be specified as optional variable.
The optional trim for character array items is available.
The optional direction (defult is column: is_col=.true.) could be choosen.

The test example:
```fortran
program strjoin_array

    use stringifor
    implicit none

    type(string), allocatable :: strings_arr(:, :)
    character(len=10)         :: chars_arr(3, 2)
    logical                   :: test_passed(5)
    logical                   :: chars_test_passed(9)

    strings_arr = reshape( source = &
                              [string('one'), string('two'), string('three'),  &
                               string('ONE'), string('TWO'), string('THREE')], &
                               shape = [3, 2] )

    test_passed(1) = all( strjoin(array=strings_arr) == &
                          reshape([string('onetwothree'), string('ONETWOTHREE')], &
                          shape = [2]) )

    test_passed(2) = all( strjoin(array=strings_arr, sep='_') == &
                          reshape([string('one_two_three'), string('ONE_TWO_THREE')], &
                          shape = [2]) )

    test_passed(3) = all( strjoin(array=strings_arr, is_col=.false.) == &
                          reshape([string('oneONE'), string('twoTWO'), string('threeTHREE')], &
                          shape = [3]) )

    test_passed(4) = all( strjoin(array=strings_arr, sep='_', is_col=.false.) == &
                          reshape([string('one_ONE'), string('two_TWO'), string('three_THREE')], &
                          shape = [3]) )

    call strings_arr(2, 1)%free
    test_passed(5) = all( strjoin(array=strings_arr, sep='_', is_col=.false.) == &
                          reshape([string('one_ONE'), string('TWO'), string('three_THREE')], &
                          shape = [3]) )

    print '(L1)', all(test_passed)


    chars_arr(:, 1) = ['one       ', 'two       ', 'three     ']
    chars_arr(:, 2) = ['ONE       ', 'TWO       ', 'THREE     ']

    chars_test_passed(1) = all( strjoin(array=chars_arr) == &
                          reshape([string('onetwothree'), string('ONETWOTHREE')], &
                          shape = [2]) )

    chars_test_passed(2) = all( strjoin(array=chars_arr, is_trim=.false.) ==  &
                          reshape([string('one       two       three     '),  &
                                   string('ONE       TWO       THREE     ')], &
                          shape = [2]) )

    chars_test_passed(3) = all( strjoin(array=chars_arr, sep='_') == &
                          reshape([string('one_two_three'), string('ONE_TWO_THREE')], &
                          shape = [2]) )

    chars_test_passed(4) = all( strjoin(array=chars_arr, sep='_', is_trim=.false.) ==  &
                          reshape([string('one       _two       _three     '),  &
                                   string('ONE       _TWO       _THREE     ')], &
                          shape = [2]) )

    chars_test_passed(5) = all( strjoin(array=chars_arr, is_col=.false.) == &
                          reshape([string('oneONE'), string('twoTWO'), string('threeTHREE')], &
                          shape = [3]) )

    chars_test_passed(6) = all( strjoin(array=chars_arr, is_trim=.false., is_col=.false.) ==  &
                          reshape([string('one       ONE       '),  &
                                   string('two       TWO       '),  &
                                   string('three     THREE     ')], &
                          shape = [3]) )

    chars_test_passed(7) = all( strjoin(array=chars_arr, sep='_', is_col=.false.) == &
                          reshape([string('one_ONE'), string('two_TWO'), string('three_THREE')], &
                          shape = [3]) )

    chars_test_passed(8) = all( strjoin(array=chars_arr, sep='_', is_trim=.false., is_col=.false.) ==  &
                          reshape([string('one       _ONE       '),  &
                                   string('two       _TWO       '),  &
                                   string('three     _THREE     ')], &
                          shape = [3]) )

    chars_arr(2,1) = ''
    chars_test_passed(9) = all( strjoin(array=chars_arr, sep='_', is_col=.false.) ==  &
                          reshape([string('one_ONE'),  &
                                   string('TWO'),  &
                                   string('three_THREE')], &
                          shape = [3]) )

    print '(L1)', all(chars_test_passed)

end program strjoin_array
```

### CODE REVIEW

**Comment by szaghi** [comment]
Wow, thank you very much!

I am out of office (due to covid-19 contagion) thus I cannot review the PR, but I trust you. Thank you again.

**Comment by szaghi** [comment]
I will merge this soon, I like to check the travis error, maybe tomorrow I will able to do it

**Comment by band-a-prend** [comment]
> Wow, thank you very much!
> 
> I am out of office (due to covid-19 contagion) thus I cannot review the PR, but I trust you. Thank you again.

I tested to build example only for gcc-9.2.0.
I skipped internal tests with more empty array items
because of it depends on already implemented functions.

Please recheck code if you will have time
as I rare write something especially in fortran :(

The explicitly defined strings literals in test_passed expressions are
used because I have no success to use smth. like
`reshape = ( source = [strings_arr(1,1)//strings_arr(2,1)//strings_arr(3,1), ...` etc.
Maybe I forgot to add something in this attempts.

Sorry that I still don't add new stringifor_string_t_*.f90 test files (or are they generated automatically as I could see from CI test results?)
and didn't run local tests the entire library.

The error in `exe/doctests-src/stringifor_string_t/stringifor_string_t-doctest-44.f90:8:1:`
\- I forgot to rename chars_test_passed to test_passed in doctests.
I'll rebase soon.

**Comment by band-a-prend** [comment]
@szaghi 
Hello. Should I add standalone test-files to this pull request? 
Or maybe rebase commits to trigger check after new changes?

**Comment by szaghi** [comment]
@band-a-prend I am very sorry for my delay, but these are strange months.

Thank you very much for the help, it is really appreciated.

**Comment by band-a-prend** [comment]
Thank you for merge.

It's ok, the situation of this year created confusion with time.

p.s.  
In april I created the packges for Gentoo Linux in GURU (gentoo users) repository for [FoBiS](https://github.com/gentoo-mirror/guru/tree/master/dev-util/FoBiS) (package supports base features) and [StringiFor](https://github.com/gentoo-mirror/guru/tree/master/dev-libs/StringiFor). The StringiFor and it's submodules aren't tagged but it isn't problem.

Hope I will have time to inverstigate errors of BeFoR64 doc-tests on GCC.

**Comment by szaghi** [comment]
@band-a-prend Thank you very much.

Cheers

**Pull request merged**
