### PR TITLE
update cmake with config adapted from PENF

### PR DESCRIPTION
**Pull request by kostyfisik**
Needed for https://github.com/szaghi/FiNeR/pull/13

### CODE REVIEW

**Comment by szaghi** [comment]
I am closing this, some things happened during this long period, feel free to remake di PR for the new versions.

Cheers

**Comment by kostyfisik** [comment]
How I should modify PR to get it accepted? It looks like at the moment project still uses old cmake2 style for build....

**Comment by szaghi** [comment]
@kostyfisik sorry, simply rebase it on the latest master branch, I will happy to accept it immediately. I had missed this PR at the time, my bad, I am trying to re-up-to-date all now

**Comment by kostyfisik** [comment]
@szaghi this depends on https://github.com/szaghi/BeFoR64/pull/13

**Comment by szaghi** [comment]
@kostyfisik I missed it also, I am going to accept it

**Comment by szaghi** [comment]
@kostyfisik PR of BeFoR64 accepted

**Pull request closed without merging**
