### PR TITLE
Support Defined I/O for GCC Fortran >= 7.x.y

### PR DESCRIPTION
**Pull request by 14NGiestas**
Solution proposed by:
https://github.com/szaghi/StringiFor/issues/20#issuecomment-447919797

### CODE REVIEW

**Comment by szaghi** [comment]
@14NGiestas 

Hi, thank you very much for your patch. Do you have applied it to the latest StringiFor release?

**Comment by szaghi** [comment]
Ok, I have merged blindly :-)

**Comment by szaghi** [comment]
Thank you again @14NGiestas

**Comment by 14NGiestas** [comment]
I don't remember the exact errors I was facing, something related to duplicate interfaces declared
I'll verify and test GCC<7 and ICC a little bit more, just in case. Right now, I'm compiling the GCC 6.

**EDIT**: I think the lines [14-17](https://github.com/szaghi/StringiFor/blob/fa437973e88864b08b41a9628cb0047a8e13933d/src/lib/stringifor_string_t.F90#L14-L17) of stringifor_string_t.F90 and the lines [8-11](https://github.com/szaghi/StringiFor/blob/fa437973e88864b08b41a9628cb0047a8e13933d/src/lib/stringifor.F90#L8-L11) of stringifor.F90 aren't needed.
The section [243-287](https://github.com/szaghi/StringiFor/blob/fa437973e88864b08b41a9628cb0047a8e13933d/src/lib/stringifor_string_t.F90#L243-L287) isn't needed as well, since the "generic" overloading works as long as the main object is public, it seems to work in both gfortran-9 and intel (all tests passing).

**Comment by szaghi** [comment]
@14NGiestas @band-a-prend 

I am sorry for my delay: I am currently try to fix some issues with Intel Fortran Compilers (2018 and 2019 that behaves differently) and trying to verify if I am violating the standard in some way. Thus my libraries can temporary work *randomly*. Please, be patient few days

**Pull request merged**
